using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EventLibrary : MonoBehaviour 
{

	public Dictionary<string, Event> allEvents;
    public Dictionary<string, Encounter> allEncounters;
    
	void Awake () 
	{
		allEvents = new Dictionary<string, Event> ();
        //

        Encounter bHive = new Encounter();

        Event bHiveInit = new Event();
		bHiveInit.mainDescription = "The humans spot a beehive high up in the branches of a tree, a delectable golden liquid dripping from within it.";
		bHiveInit.bOneText = "Harvest";
        bHiveInit.bTwoText = "Leave";
		bHiveInit.bThreeText = " ";
		bHiveInit.bFourText = " ";
		bHiveInit.bFiveText = " ";
		bHiveInit.mainImage = Resources.Load<Sprite> ("EventImages/BeeHive/beehive");
		bHiveInit.childImage = null;
		bHiveInit.leaderImage = null;
		bHiveInit.shamanImage = null;
		bHiveInit.dogImage = null;
		bHiveInit.hunterImage = null;
		bHiveInit.displayedImage = bHiveInit.mainImage;
		bHiveInit.bOneLinkedEvent = "Harvest";
		bHiveInit.bTwoLinkedEvent = "Leave";
		bHiveInit.bThreeLinkedEvent = "Something else";
		bHiveInit.bFourLinkedEvent = "Something else";
		bHiveInit.bFiveLinkedEvent = "Something else";
        bHiveInit.statChange = [StatChange.addFood, StatChange.addFood, StatChange.addWisdom];

        bHive.Events.Add ("Init", bHiveInit);
        //
        Event bHiveHarvest = new Event();
		bHiveHarvest.mainDescription = "Harvest.";
		bHiveHarvest.bOneText = "Leader";
		bHiveHarvest.bTwoText = "Hunter";
		bHiveHarvest.bThreeText = "Child";
		bHiveHarvest.bFourText = "Dog";
		bHiveHarvest.bFiveText = "Shaman";
		bHiveHarvest.mainImage = Resources.Load<Sprite> ("EventImages/BeeHive/beehive");
		bHiveHarvest.childImage = null;
		bHiveHarvest.leaderImage = null;
		bHiveHarvest.shamanImage = null;
		bHiveHarvest.dogImage = null;
		bHiveHarvest.hunterImage = null;
		bHiveHarvest.displayedImage = bHiveInit.mainImage;
		bHiveHarvest.bOneLinkedEvent = "HarvestLeader";
		bHiveHarvest.bTwoLinkedEvent = "HarvestHunter";
		bHiveHarvest.bThreeLinkedEvent = "HarvestChild";
		bHiveHarvest.bFourLinkedEvent = "HarvestDog";
		bHiveHarvest.bFiveLinkedEvent = "HarvestShaman";
        bHive.Events.Add ("Harvest", bHiveHarvest);
        //
        Event bHiveHarvestLeader = new Event() {
            mainDescription = "The Leader picks up the Child and hurls him at the beehive, effectively knocking it from its branch. The bees, alarmed by this gross display of recklessness, flee from their hive. The Child, only slightly bruised, picks up the empty hive and harvests the honey from within. (+food + optimism)",
            bOneText = " ",
            bTwoText = " ",
            bThreeText = " ",
            bFourText = " ",
            bFiveText = " ",
            mainImage = Resources.Load<Sprite>("EventImages/BeeHive/beehive"),
            childImage = null,
            leaderImage = null,
            shamanImage = null,
            dogImage = null,
            hunterImage = null,
            bOneLinkedEvent = "Something else",
            bTwoLinkedEvent = "Something else",
            bThreeLinkedEvent = "Something else",
            bFourLinkedEvent = "Something else",
            bFiveLinkedEvent = "Something else"
        };
        bHiveHarvestLeader.displayedImage = bHiveHarvestLeader.mainImage;
        bHive.Events.Add("HarvestLeader", bHiveHarvestLeader);
        //
        Event bHiveHarvestHunter = new Event();
        bHiveHarvestHunter.mainDescription = "The Hunter launches a spear at the hive, and it drops to the ground, cloven perfectly in two. The bees bow to the Hunter’s expertise, and name him their Queen. (++food + optimism)";
        bHiveHarvestHunter.bOneText = " ";
        bHiveHarvestHunter.bTwoText = " ";
        bHiveHarvestHunter.bThreeText = " ";
        bHiveHarvestHunter.bFourText = " ";
        bHiveHarvestHunter.bFiveText = " ";
        bHiveHarvestHunter.mainImage = Resources.Load<Sprite>("EventImages/BeeHive/beehive");
        bHiveHarvestHunter.childImage = null;
        bHiveHarvestHunter.leaderImage = null;
        bHiveHarvestHunter.shamanImage = null;
        bHiveHarvestHunter.dogImage = null;
        bHiveHarvestHunter.hunterImage = null;
        bHiveHarvestHunter.displayedImage = bHiveHarvestHunter.mainImage;
        bHiveHarvestHunter.bOneLinkedEvent = "Something else";
        bHiveHarvestHunter.bTwoLinkedEvent = "Something else";
        bHiveHarvestHunter.bThreeLinkedEvent = "Something else";
        bHiveHarvestHunter.bFourLinkedEvent = "Something else";
        bHiveHarvestHunter.bFiveLinkedEvent = "Something else";
        bHive.Events.Add("HarvestHunter", bHiveHarvestHunter);
        //
        Event bHiveHarvestChild = new Event();
        bHiveHarvestChild.mainDescription = "The Child climbs the tree and knocks the hive from its branch. It crashes to the ground, and a swarm of enraged bees sting the group, much to the Child’s amusement. Turns out bees sting. (+wisdom)";
        bHiveHarvestChild.bOneText = " ";
        bHiveHarvestChild.bTwoText = " ";
        bHiveHarvestChild.bThreeText = " ";
        bHiveHarvestChild.bFourText = " ";
        bHiveHarvestChild.bFiveText = " ";
        bHiveHarvestChild.mainImage = Resources.Load<Sprite>("EventImages/BeeHive/beehive");
        bHiveHarvestChild.childImage = null;
        bHiveHarvestChild.leaderImage = null;
        bHiveHarvestChild.shamanImage = null;
        bHiveHarvestChild.dogImage = null;
        bHiveHarvestChild.hunterImage = null;
        bHiveHarvestChild.displayedImage = bHiveHarvestChild.mainImage;
        bHiveHarvestChild.bOneLinkedEvent = "Something else";
        bHiveHarvestChild.bTwoLinkedEvent = "Something else";
        bHiveHarvestChild.bThreeLinkedEvent = "Something else";
        bHiveHarvestChild.bFourLinkedEvent = "Something else";
        bHiveHarvestChild.bFiveLinkedEvent = "Something else";
        bHive.Events.Add("HarvestChild", bHiveHarvestChild);
        //
        Event bHiveHarvestDog = new Event();
        bHiveHarvestDog.mainDescription = "The Dog barks continuously at the hive, to no avail. The group applaud his efforts. (+optimism)";
        bHiveHarvestDog.bOneText = " ";
        bHiveHarvestDog.bTwoText = " ";
        bHiveHarvestDog.bThreeText = " ";
        bHiveHarvestDog.bFourText = " ";
        bHiveHarvestDog.bFiveText = " ";
        bHiveHarvestDog.mainImage = Resources.Load<Sprite>("EventImages/BeeHive/beehive");
        bHiveHarvestDog.childImage = null;
        bHiveHarvestDog.leaderImage = null;
        bHiveHarvestDog.shamanImage = null;
        bHiveHarvestDog.dogImage = null;
        bHiveHarvestDog.hunterImage = null;
        bHiveHarvestDog.displayedImage = bHiveHarvestDog.mainImage;
        bHiveHarvestDog.bOneLinkedEvent = "Something else";
        bHiveHarvestDog.bTwoLinkedEvent = "Something else";
        bHiveHarvestDog.bThreeLinkedEvent = "Something else";
        bHiveHarvestDog.bFourLinkedEvent = "Something else";
        bHiveHarvestDog.bFiveLinkedEvent = "Something else";
        bHive.Events.Add("HarvestDog", bHiveHarvestDog);
        //
        Event bHiveHarvestShaman = new Event();
        bHiveHarvestShaman.mainDescription = "The Shaman attempts to charm the bees away from the hive with a crudely crafted ukulebee. It ends badly. (+wisdom)";
        bHiveHarvestShaman.bOneText = " ";
        bHiveHarvestShaman.bTwoText = " ";
        bHiveHarvestShaman.bThreeText = " ";
        bHiveHarvestShaman.bFourText = " ";
        bHiveHarvestShaman.bFiveText = " ";
        bHiveHarvestShaman.mainImage = Resources.Load<Sprite>("EventImages/BeeHive/beehive");
        bHiveHarvestShaman.childImage = null;
        bHiveHarvestShaman.leaderImage = null;
        bHiveHarvestShaman.shamanImage = null;
        bHiveHarvestShaman.dogImage = null;
        bHiveHarvestShaman.hunterImage = null;
        bHiveHarvestShaman.displayedImage = bHiveHarvestShaman.mainImage;
        bHiveHarvestShaman.bOneLinkedEvent = "Something else";
        bHiveHarvestShaman.bTwoLinkedEvent = "Something else";
        bHiveHarvestShaman.bThreeLinkedEvent = "Something else";
        bHiveHarvestShaman.bFourLinkedEvent = "Something else";
        bHiveHarvestShaman.bFiveLinkedEvent = "Something else";
        bHive.Events.Add("HarvestShaman", bHiveHarvestShaman);
        //
        Event bHiveLeave = new Event();
        bHiveLeave.mainDescription = "The group wisely decide to leave the beehive alone, and trudge off having never known the taste of honey. (+wisdom)";
        bHiveLeave.bOneText = " ";
        bHiveLeave.bTwoText = " ";
        bHiveLeave.bThreeText = " ";
        bHiveLeave.bFourText = " ";
        bHiveLeave.bFiveText = " ";
        bHiveLeave.mainImage = Resources.Load<Sprite>("EventImages/BeeHive/beehive");
        bHiveLeave.childImage = null;
        bHiveLeave.leaderImage = null;
        bHiveLeave.shamanImage = null;
        bHiveLeave.dogImage = null;
        bHiveLeave.hunterImage = null;
        bHiveLeave.displayedImage = bHiveLeave.mainImage;
        bHiveLeave.bOneLinkedEvent = "Something else";
        bHiveLeave.bTwoLinkedEvent = "Something else";
        bHiveLeave.bThreeLinkedEvent = "Something else";
        bHiveLeave.bFourLinkedEvent = "Something else";
        bHiveLeave.bFiveLinkedEvent = "Something else";
        bHive.Events.Add("Leave", bHiveLeave);

        allEncounters.Add("bHive", bHive);
        //
        //
        //
        Event fireInit = new Event();
        fireInit.mainDescription = "Dark, brooding clouds gather. Lightning splits from the sky above and ignites one of the trees into a pillar of fire.";
        fireInit.bOneText = "Play with the fire";
        fireInit.bTwoText = "Pray to the fire";
        fireInit.bThreeText = " ";
        fireInit.bFourText = " ";
        fireInit.bFiveText = " ";
        fireInit.mainImage = Resources.Load<Sprite>(" ");
        fireInit.childImage = null;
        fireInit.leaderImage = null;
        fireInit.shamanImage = null;
        fireInit.dogImage = null;
        fireInit.hunterImage = null;
        fireInit.displayedImage = fireInit.mainImage;
        fireInit.bOneLinkedEvent = "firePlay";
        fireInit.bTwoLinkedEvent = "firePray";
        fireInit.bThreeLinkedEvent = "Something else";
        fireInit.bFourLinkedEvent = "Something else";
        fireInit.bFiveLinkedEvent = "Something else";
        allEvents.Add("fireInit", fireInit);
        //
        Event firePlay = new Event();
        firePlay.mainDescription = "Play with the fire.";
        firePlay.bOneText = "Leader";
        firePlay.bTwoText = "Hunter";
        firePlay.bThreeText = "Child";
        firePlay.bFourText = "Dog";
        firePlay.bFiveText = " ";
        firePlay.mainImage = Resources.Load<Sprite>(" ");
        firePlay.childImage = null;
        firePlay.leaderImage = null;
        firePlay.shamanImage = null;
        firePlay.dogImage = null;
        firePlay.hunterImage = null;
        firePlay.displayedImage = fireInit.mainImage;
        firePlay.bOneLinkedEvent = "firePlayLeader";
        firePlay.bTwoLinkedEvent = "firePlayHunter";
        firePlay.bThreeLinkedEvent = "firePlayChild";
        firePlay.bFourLinkedEvent = "firePlayDog";
        firePlay.bFiveLinkedEvent = "Something else";
        allEvents.Add("firePlay", firePlay);
        //
        Event firePlayLeader = new Event();
        firePlayLeader.mainDescription = "The Leader stretches out his fingers towards the dancing flames, only to have his hand badly burnt. The Shaman, most put out, tends to his wounds as he weeps softly into his unburnt palm. (+wisdom)";
        firePlayLeader.bOneText = " ";
        firePlayLeader.bTwoText = " ";
        firePlayLeader.bThreeText = " ";
        firePlayLeader.bFourText = " ";
        firePlayLeader.bFiveText = " ";
        firePlayLeader.mainImage = Resources.Load<Sprite>(" ");
        firePlayLeader.childImage = null;
        firePlayLeader.leaderImage = null;
        firePlayLeader.shamanImage = null;
        firePlayLeader.dogImage = null;
        firePlayLeader.hunterImage = null;
        firePlayLeader.displayedImage = firePlayLeader.mainImage;
        firePlayLeader.bOneLinkedEvent = "Something else";
        firePlayLeader.bTwoLinkedEvent = "Something else";
        firePlayLeader.bThreeLinkedEvent = "Something else";
        firePlayLeader.bFourLinkedEvent = "Something else";
        firePlayLeader.bFiveLinkedEvent = "Something else";
        allEvents.Add("firePlayLeader", firePlayLeader);
        //
        Event firePlayHunter = new Event();
        firePlayHunter.mainDescription = "The Hunter shoots a squirrel from a nearby tree and roasts it over the fire until it is golden brown. All of the humans agree it is delicious, but the Shaman thinks it needs some seasoning. (+food + wisdom)";
        firePlayHunter.bOneText = " ";
        firePlayHunter.bTwoText = " ";
        firePlayHunter.bThreeText = " ";
        firePlayHunter.bFourText = " ";
        firePlayHunter.bFiveText = " ";
        firePlayHunter.mainImage = Resources.Load<Sprite>(" ");
        firePlayHunter.childImage = null;
        firePlayHunter.leaderImage = null;
        firePlayHunter.shamanImage = null;
        firePlayHunter.dogImage = null;
        firePlayHunter.hunterImage = null;
        firePlayHunter.displayedImage = firePlayHunter.mainImage;
        firePlayHunter.bOneLinkedEvent = "Something else";
        firePlayHunter.bTwoLinkedEvent = "Something else";
        firePlayHunter.bThreeLinkedEvent = "Something else";
        firePlayHunter.bFourLinkedEvent = "Something else";
        firePlayHunter.bFiveLinkedEvent = "Something else";
        allEvents.Add("firePlayHunter", firePlayHunter);
        //
        Event firePlayChild = new Event();
        firePlayChild.mainDescription = "The Child knows not to play with fire. (+wisdom)";
        firePlayChild.bOneText = " ";
        firePlayChild.bTwoText = " ";
        firePlayChild.bThreeText = " ";
        firePlayChild.bFourText = " ";
        firePlayChild.bFiveText = " ";
        firePlayChild.mainImage = Resources.Load<Sprite>(" ");
        firePlayChild.childImage = null;
        firePlayChild.leaderImage = null;
        firePlayChild.shamanImage = null;
        firePlayChild.dogImage = null;
        firePlayChild.hunterImage = null;
        firePlayChild.displayedImage = firePlayChild.mainImage;
        firePlayChild.bOneLinkedEvent = "Something else";
        firePlayChild.bTwoLinkedEvent = "Something else";
        firePlayChild.bThreeLinkedEvent = "Something else";
        firePlayChild.bFourLinkedEvent = "Something else";
        firePlayChild.bFiveLinkedEvent = "Something else";
        allEvents.Add("firePlayChild", firePlayChild);
        //
        Event firePlayDog = new Event();
        firePlayDog.mainDescription = "The Dog urinates on the fire and puts it out with great efficiency. (+wisdom)";
        firePlayDog.bOneText = " ";
        firePlayDog.bTwoText = " ";
        firePlayDog.bThreeText = " ";
        firePlayDog.bFourText = " ";
        firePlayDog.bFiveText = " ";
        firePlayDog.mainImage = Resources.Load<Sprite>(" ");
        firePlayDog.childImage = null;
        firePlayDog.leaderImage = null;
        firePlayDog.shamanImage = null;
        firePlayDog.dogImage = null;
        firePlayDog.hunterImage = null;
        firePlayDog.displayedImage = firePlayDog.mainImage;
        firePlayDog.bOneLinkedEvent = "Something else";
        firePlayDog.bTwoLinkedEvent = "Something else";
        firePlayDog.bThreeLinkedEvent = "Something else";
        firePlayDog.bFourLinkedEvent = "Something else";
        firePlayDog.bFiveLinkedEvent = "Something else";
        allEvents.Add("firePlayDog", firePlayDog);
        //
        Event firePray = new Event();
        firePray.mainDescription = "The Shaman bows down and prays into the fire. The fire dances majestically in a way that implies it’s trying to communicate. No one understands what the fire is saying. (+optimism)";
        firePray.bOneText = " ";
        firePray.bTwoText = " ";
        firePray.bThreeText = " ";
        firePray.bFourText = " ";
        firePray.bFiveText = " ";
        firePray.mainImage = Resources.Load<Sprite>(" ");
        firePray.childImage = null;
        firePray.leaderImage = null;
        firePray.shamanImage = null;
        firePray.dogImage = null;
        firePray.hunterImage = null;
        firePray.displayedImage = firePray.mainImage;
        firePray.bOneLinkedEvent = "Something else";
        firePray.bTwoLinkedEvent = "Something else";
        firePray.bThreeLinkedEvent = "Something else";
        firePray.bFourLinkedEvent = "Something else";
        firePray.bFiveLinkedEvent = "Something else";
        allEvents.Add("firePray", firePray);
        //
        //
        //
        Event hideAndSeekInit = new Event();
        hideAndSeekInit.mainDescription = "The Child is horribly bored and demands to play hide and seek.";
        hideAndSeekInit.bOneText = "Have the Leader play with the Child";
        hideAndSeekInit.bTwoText = "Have the Hunter play with the Child";
        hideAndSeekInit.bThreeText = "Have the Shaman play with the Child";
        hideAndSeekInit.bFourText = "Have the Dog play with the Child";
        hideAndSeekInit.bFiveText = " ";
        hideAndSeekInit.mainImage = Resources.Load<Sprite>(" ");
        hideAndSeekInit.childImage = null;
        hideAndSeekInit.leaderImage = null;
        hideAndSeekInit.shamanImage = null;
        hideAndSeekInit.dogImage = null;
        hideAndSeekInit.hunterImage = null;
        hideAndSeekInit.displayedImage = hideAndSeekInit.mainImage;
        hideAndSeekInit.bOneLinkedEvent = "hideAndSeekLeader";
        hideAndSeekInit.bTwoLinkedEvent = "hideAndSeekHunter";
        hideAndSeekInit.bThreeLinkedEvent = "hideAndSeekShaman";
        hideAndSeekInit.bFourLinkedEvent = "hideAndSeekDog";
        hideAndSeekInit.bFiveLinkedEvent = "Something else";
        allEvents.Add("hideAndSeekInit", hideAndSeekInit);
        //
        Event hideAndSeekLeader = new Event();
        hideAndSeekLeader.mainDescription = "The Leader seeks a hiding place in the nearest bush he can find, unwilling to exert much energy. Unbeknownst to him, the bush is full of stinging nettles. He is itchy for the next hour. (+wisdom)";
        hideAndSeekLeader.bOneText = " ";
        hideAndSeekLeader.bTwoText = " ";
        hideAndSeekLeader.bThreeText = " ";
        hideAndSeekLeader.bFourText = " ";
        hideAndSeekLeader.bFiveText = " ";
        hideAndSeekLeader.mainImage = Resources.Load<Sprite>(" ");
        hideAndSeekLeader.childImage = null;
        hideAndSeekLeader.leaderImage = null;
        hideAndSeekLeader.shamanImage = null;
        hideAndSeekLeader.dogImage = null;
        hideAndSeekLeader.hunterImage = null;
        hideAndSeekLeader.displayedImage = hideAndSeekLeader.mainImage;
        hideAndSeekLeader.bOneLinkedEvent = "Something else";
        hideAndSeekLeader.bTwoLinkedEvent = "Something else";
        hideAndSeekLeader.bThreeLinkedEvent = "Something else";
        hideAndSeekLeader.bFourLinkedEvent = "Something else";
        hideAndSeekLeader.bFiveLinkedEvent = "Something else";
        allEvents.Add("hideAndSeekLeader", hideAndSeekLeader);
        //
        Event hideAndSeekHunter = new Event();
        hideAndSeekHunter.mainDescription = "The Hunter vanishes in a flash and cannot be found until the Child eventually gives up. (+optimism)";
        hideAndSeekHunter.bOneText = " ";
        hideAndSeekHunter.bTwoText = " ";
        hideAndSeekHunter.bThreeText = " ";
        hideAndSeekHunter.bFourText = " ";
        hideAndSeekHunter.bFiveText = " ";
        hideAndSeekHunter.mainImage = Resources.Load<Sprite>(" ");
        hideAndSeekHunter.childImage = null;
        hideAndSeekHunter.leaderImage = null;
        hideAndSeekHunter.shamanImage = null;
        hideAndSeekHunter.dogImage = null;
        hideAndSeekHunter.hunterImage = null;
        hideAndSeekHunter.displayedImage = hideAndSeekHunter.mainImage;
        hideAndSeekHunter.bOneLinkedEvent = "Something else";
        hideAndSeekHunter.bTwoLinkedEvent = "Something else";
        hideAndSeekHunter.bThreeLinkedEvent = "Something else";
        hideAndSeekHunter.bFourLinkedEvent = "Something else";
        hideAndSeekHunter.bFiveLinkedEvent = "Something else";
        allEvents.Add("hideAndSeekHunter", hideAndSeekHunter);
        //
        Event hideAndSeekShaman = new Event();
        hideAndSeekShaman.mainDescription = "The Shaman creates a disguise from nearby foliage, blending her perfectly with her surroundings. The is not found for some time. (+wisdom)";
        hideAndSeekShaman.bOneText = " ";
        hideAndSeekShaman.bTwoText = " ";
        hideAndSeekShaman.bThreeText = " ";
        hideAndSeekShaman.bFourText = " ";
        hideAndSeekShaman.bFiveText = " ";
        hideAndSeekShaman.mainImage = Resources.Load<Sprite>(" ");
        hideAndSeekShaman.childImage = null;
        hideAndSeekShaman.leaderImage = null;
        hideAndSeekShaman.shamanImage = null;
        hideAndSeekShaman.dogImage = null;
        hideAndSeekShaman.hunterImage = null;
        hideAndSeekShaman.displayedImage = hideAndSeekShaman.mainImage;
        hideAndSeekShaman.bOneLinkedEvent = "Something else";
        hideAndSeekShaman.bTwoLinkedEvent = "Something else";
        hideAndSeekShaman.bThreeLinkedEvent = "Something else";
        hideAndSeekShaman.bFourLinkedEvent = "Something else";
        hideAndSeekShaman.bFiveLinkedEvent = "Something else";
        allEvents.Add("hideAndSeekShaman", hideAndSeekShaman);
        //
        Event hideAndSeekDog = new Event();
        hideAndSeekDog.mainDescription = "The Dog does not comprehend the concept of hide and seek, but somehow comes out of the experience with many belly rubs. (+wisdom)";
        hideAndSeekDog.bOneText = " ";
        hideAndSeekDog.bTwoText = " ";
        hideAndSeekDog.bThreeText = " ";
        hideAndSeekDog.bFourText = " ";
        hideAndSeekDog.bFiveText = " ";
        hideAndSeekDog.mainImage = Resources.Load<Sprite>(" ");
        hideAndSeekDog.childImage = null;
        hideAndSeekDog.leaderImage = null;
        hideAndSeekDog.shamanImage = null;
        hideAndSeekDog.dogImage = null;
        hideAndSeekDog.hunterImage = null;
        hideAndSeekDog.displayedImage = hideAndSeekDog.mainImage;
        hideAndSeekDog.bOneLinkedEvent = "Something else";
        hideAndSeekDog.bTwoLinkedEvent = "Something else";
        hideAndSeekDog.bThreeLinkedEvent = "Something else";
        hideAndSeekDog.bFourLinkedEvent = "Something else";
        hideAndSeekDog.bFiveLinkedEvent = "Something else";
        allEvents.Add("hideAndSeekDog", hideAndSeekDog);
        //
        //
        //
        Event vineInit = new Event();
        vineInit.mainDescription = "A long, sturdy-looking vine trails from the branch of a tree.";
        vineInit.bOneText = "Swing from the vine";
        vineInit.bTwoText = "Climb the vine";
        vineInit.bThreeText = " ";
        vineInit.bFourText = " ";
        vineInit.bFiveText = " ";
        vineInit.mainImage = Resources.Load<Sprite>(" ");
        vineInit.childImage = null;
        vineInit.leaderImage = null;
        vineInit.shamanImage = null;
        vineInit.dogImage = null;
        vineInit.hunterImage = null;
        vineInit.displayedImage = vineInit.mainImage;
        vineInit.bOneLinkedEvent = "vineSwing";
        vineInit.bTwoLinkedEvent = "vineClimb";
        vineInit.bThreeLinkedEvent = "Something else";
        vineInit.bFourLinkedEvent = "Something else";
        vineInit.bFiveLinkedEvent = "Something else";
        allEvents.Add("vineInit", vineInit);
        //
        Event vineSwing = new Event();
        vineSwing.mainDescription = "Swing from the vine";
        vineSwing.bOneText = "Hunter";
        vineSwing.bTwoText = "Child";
        vineSwing.bThreeText = " ";
        vineSwing.bFourText = " ";
        vineSwing.bFiveText = " ";
        vineSwing.mainImage = Resources.Load<Sprite>(" ");
        vineSwing.childImage = null;
        vineSwing.leaderImage = null;
        vineSwing.shamanImage = null;
        vineSwing.dogImage = null;
        vineSwing.hunterImage = null;
        vineSwing.displayedImage = vineInit.mainImage;
        vineSwing.bOneLinkedEvent = "vineSwingHunter";
        vineSwing.bTwoLinkedEvent = "vineSwingChild";
        vineSwing.bThreeLinkedEvent = "Something else";
        vineSwing.bFourLinkedEvent = "Something else";
        vineSwing.bFiveLinkedEvent = "Something else";
        allEvents.Add("vineSwing", vineSwing);
        //
        Event vineSwingHunter = new Event();
        vineSwingHunter.mainDescription = "The Hunter swings on the vine, screaming like Tarzan. (+optimism)";
        vineSwingHunter.bOneText = " ";
        vineSwingHunter.bTwoText = " ";
        vineSwingHunter.bThreeText = " ";
        vineSwingHunter.bFourText = " ";
        vineSwingHunter.bFiveText = " ";
        vineSwingHunter.mainImage = Resources.Load<Sprite>(" ");
        vineSwingHunter.childImage = null;
        vineSwingHunter.leaderImage = null;
        vineSwingHunter.shamanImage = null;
        vineSwingHunter.dogImage = null;
        vineSwingHunter.hunterImage = null;
        vineSwingHunter.displayedImage = vineSwingHunter.mainImage;
        vineSwingHunter.bOneLinkedEvent = "Something else";
        vineSwingHunter.bTwoLinkedEvent = "Something else";
        vineSwingHunter.bThreeLinkedEvent = "Something else";
        vineSwingHunter.bFourLinkedEvent = "Something else";
        vineSwingHunter.bFiveLinkedEvent = "Something else";
        allEvents.Add("vineSwingHunter", vineSwingHunter);
        //
        Event vineSwingChild = new Event();
        vineSwingChild.mainDescription = "The Child has a truly fantastic time swinging on the vine. (+optimism)";
        vineSwingChild.bOneText = " ";
        vineSwingChild.bTwoText = " ";
        vineSwingChild.bThreeText = " ";
        vineSwingChild.bFourText = " ";
        vineSwingChild.bFiveText = " ";
        vineSwingChild.mainImage = Resources.Load<Sprite>(" ");
        vineSwingChild.childImage = null;
        vineSwingChild.leaderImage = null;
        vineSwingChild.shamanImage = null;
        vineSwingChild.dogImage = null;
        vineSwingChild.hunterImage = null;
        vineSwingChild.displayedImage = vineSwingChild.mainImage;
        vineSwingChild.bOneLinkedEvent = "Something else";
        vineSwingChild.bTwoLinkedEvent = "Something else";
        vineSwingChild.bThreeLinkedEvent = "Something else";
        vineSwingChild.bFourLinkedEvent = "Something else";
        vineSwingChild.bFiveLinkedEvent = "Something else";
        allEvents.Add("vineSwingChild", vineSwingChild);
        //
        Event vineClimb = new Event();
        vineClimb.mainDescription = "Climb the vine";
        vineClimb.bOneText = "Leader";
        vineClimb.bTwoText = "Shaman";
        vineClimb.bThreeText = " ";
        vineClimb.bFourText = " ";
        vineClimb.bFiveText = " ";
        vineClimb.mainImage = Resources.Load<Sprite>(" ");
        vineClimb.childImage = null;
        vineClimb.leaderImage = null;
        vineClimb.shamanImage = null;
        vineClimb.dogImage = null;
        vineClimb.hunterImage = null;
        vineClimb.displayedImage = vineInit.mainImage;
        vineClimb.bOneLinkedEvent = "vineClimbLeader";
        vineClimb.bTwoLinkedEvent = "vineClimbShaman";
        vineClimb.bThreeLinkedEvent = "Something else";
        vineClimb.bFourLinkedEvent = "Something else";
        vineClimb.bFiveLinkedEvent = "Something else";
        allEvents.Add("vineClimb", vineClimb);
        //
        Event vineClimbLeader = new Event();
        vineClimbLeader.mainDescription = "The Leader attempts to hoist himself up using the vine, but alas, he has no upper-body strength.";
        vineClimbLeader.bOneText = " ";
        vineClimbLeader.bTwoText = " ";
        vineClimbLeader.bThreeText = " ";
        vineClimbLeader.bFourText = " ";
        vineClimbLeader.bFiveText = " ";
        vineClimbLeader.mainImage = Resources.Load<Sprite>(" ");
        vineClimbLeader.childImage = null;
        vineClimbLeader.leaderImage = null;
        vineClimbLeader.shamanImage = null;
        vineClimbLeader.dogImage = null;
        vineClimbLeader.hunterImage = null;
        vineClimbLeader.displayedImage = vineClimbLeader.mainImage;
        vineClimbLeader.bOneLinkedEvent = "Something else";
        vineClimbLeader.bTwoLinkedEvent = "Something else";
        vineClimbLeader.bThreeLinkedEvent = "Something else";
        vineClimbLeader.bFourLinkedEvent = "Something else";
        vineClimbLeader.bFiveLinkedEvent = "Something else";
        allEvents.Add("vineClimbLeader", vineClimbLeader);
        //
        Event vineClimbShaman = new Event();
        vineClimbShaman.mainDescription = "The Shaman skilfully scales the vine to find a nest of eggs admits the branches. (+food + optimism)";
        vineClimbShaman.bOneText = " ";
        vineClimbShaman.bTwoText = " ";
        vineClimbShaman.bThreeText = " ";
        vineClimbShaman.bFourText = " ";
        vineClimbShaman.bFiveText = " ";
        vineClimbShaman.mainImage = Resources.Load<Sprite>(" ");
        vineClimbShaman.childImage = null;
        vineClimbShaman.leaderImage = null;
        vineClimbShaman.shamanImage = null;
        vineClimbShaman.dogImage = null;
        vineClimbShaman.hunterImage = null;
        vineClimbShaman.displayedImage = vineClimbShaman.mainImage;
        vineClimbShaman.bOneLinkedEvent = "Something else";
        vineClimbShaman.bTwoLinkedEvent = "Something else";
        vineClimbShaman.bThreeLinkedEvent = "Something else";
        vineClimbShaman.bFourLinkedEvent = "Something else";
        vineClimbShaman.bFiveLinkedEvent = "Something else";
        allEvents.Add("vineClimbShaman", vineClimbShaman);
        //
        //
        //
        Event wolfInit = new Event();
        wolfInit.mainDescription = "The group encounter a Dire wolf. Mesmerised by its beauty, they stare at it in wonder.";
        wolfInit.bOneText = "Approach the wolf";
        wolfInit.bTwoText = "Flee";
        wolfInit.bThreeText = " ";
        wolfInit.bFourText = " ";
        wolfInit.bFiveText = " ";
        wolfInit.mainImage = Resources.Load<Sprite>(" ");
        wolfInit.childImage = null;
        wolfInit.leaderImage = null;
        wolfInit.shamanImage = null;
        wolfInit.dogImage = null;
        wolfInit.hunterImage = null;
        wolfInit.displayedImage = wolfInit.mainImage;
        wolfInit.bOneLinkedEvent = "wolfApproach";
        wolfInit.bTwoLinkedEvent = "wolfFlee";
        wolfInit.bThreeLinkedEvent = "Something else";
        wolfInit.bFourLinkedEvent = "Something else";
        wolfInit.bFiveLinkedEvent = "Something else";
        allEvents.Add("wolfInit", wolfInit);
        //
        Event wolfApproach = new Event();
        wolfApproach.mainDescription = "Approach the wolf";
        wolfApproach.bOneText = "Leader";
        wolfApproach.bTwoText = "Hunter";
        wolfApproach.bThreeText = "Dog";
        wolfApproach.bFourText = "Child";
        wolfApproach.bFiveText = "Shaman";
        wolfApproach.mainImage = Resources.Load<Sprite>(" ");
        wolfApproach.childImage = null;
        wolfApproach.leaderImage = null;
        wolfApproach.shamanImage = null;
        wolfApproach.dogImage = null;
        wolfApproach.hunterImage = null;
        wolfApproach.displayedImage = wolfInit.mainImage;
        wolfApproach.bOneLinkedEvent = "wolfApproachLeader";
        wolfApproach.bTwoLinkedEvent = "wolfApproachHunter";
        wolfApproach.bThreeLinkedEvent = "wolfApproachDog";
        wolfApproach.bFourLinkedEvent = "wolfApproachChild";
        wolfApproach.bFiveLinkedEvent = "wolfApproachShaman";
        allEvents.Add("wolfApproach", wolfApproach);
        //
        Event wolfApproachLeader = new Event();
        wolfApproachLeader.mainDescription = "The Leader approaches the wolf “Chris Pratt Jurassic World” style. The wolf decides that it doesn’t like the Leader. Long story short, the group end up running away screaming. (+wisdom)";
        wolfApproachLeader.bOneText = " ";
        wolfApproachLeader.bTwoText = " ";
        wolfApproachLeader.bThreeText = " ";
        wolfApproachLeader.bFourText = " ";
        wolfApproachLeader.bFiveText = " ";
        wolfApproachLeader.mainImage = Resources.Load<Sprite>(" ");
        wolfApproachLeader.childImage = null;
        wolfApproachLeader.leaderImage = null;
        wolfApproachLeader.shamanImage = null;
        wolfApproachLeader.dogImage = null;
        wolfApproachLeader.hunterImage = null;
        wolfApproachLeader.displayedImage = wolfApproachLeader.mainImage;
        wolfApproachLeader.bOneLinkedEvent = "Something else";
        wolfApproachLeader.bTwoLinkedEvent = "Something else";
        wolfApproachLeader.bThreeLinkedEvent = "Something else";
        wolfApproachLeader.bFourLinkedEvent = "Something else";
        wolfApproachLeader.bFiveLinkedEvent = "Something else";
        allEvents.Add("wolfApproachLeader", wolfApproachLeader);
        //
        Event wolfApproachHunter = new Event();
        wolfApproachHunter.mainDescription = "The Hunter sources the nearest stick and flings it far into the forest. The Dire wolf runs away, never to return. (+optimism)";
        wolfApproachHunter.bOneText = " ";
        wolfApproachHunter.bTwoText = " ";
        wolfApproachHunter.bThreeText = " ";
        wolfApproachHunter.bFourText = " ";
        wolfApproachHunter.bFiveText = " ";
        wolfApproachHunter.mainImage = Resources.Load<Sprite>(" ");
        wolfApproachHunter.childImage = null;
        wolfApproachHunter.leaderImage = null;
        wolfApproachHunter.shamanImage = null;
        wolfApproachHunter.dogImage = null;
        wolfApproachHunter.hunterImage = null;
        wolfApproachHunter.displayedImage = wolfApproachHunter.mainImage;
        wolfApproachHunter.bOneLinkedEvent = "Something else";
        wolfApproachHunter.bTwoLinkedEvent = "Something else";
        wolfApproachHunter.bThreeLinkedEvent = "Something else";
        wolfApproachHunter.bFourLinkedEvent = "Something else";
        wolfApproachHunter.bFiveLinkedEvent = "Something else";
        allEvents.Add("wolfApproachHunter", wolfApproachHunter);
        //
        Event wolfApproachDog = new Event();
        wolfApproachDog.mainDescription = "The Dog, sensing the similarities between the two animals, befriends the wolf, who, pleased to have a new buddy, leads the Dog to a secret stash of meat. (+food + optimism)";
        wolfApproachDog.bOneText = " ";
        wolfApproachDog.bTwoText = " ";
        wolfApproachDog.bThreeText = " ";
        wolfApproachDog.bFourText = " ";
        wolfApproachDog.bFiveText = " ";
        wolfApproachDog.mainImage = Resources.Load<Sprite>(" ");
        wolfApproachDog.childImage = null;
        wolfApproachDog.leaderImage = null;
        wolfApproachDog.shamanImage = null;
        wolfApproachDog.dogImage = null;
        wolfApproachDog.hunterImage = null;
        wolfApproachDog.displayedImage = wolfApproachDog.mainImage;
        wolfApproachDog.bOneLinkedEvent = "Something else";
        wolfApproachDog.bTwoLinkedEvent = "Something else";
        wolfApproachDog.bThreeLinkedEvent = "Something else";
        wolfApproachDog.bFourLinkedEvent = "Something else";
        wolfApproachDog.bFiveLinkedEvent = "Something else";
        allEvents.Add("wolfApproachDog", wolfApproachDog);
        //
        Event wolfApproachChild = new Event();
        wolfApproachChild.mainDescription = "The Child approaches the wolf “Chris Pratt Jurassic World” style. Turns out the wolf is a good boy. Many tummy rubs ensue. (++optimism)";
        wolfApproachChild.bOneText = " ";
        wolfApproachChild.bTwoText = " ";
        wolfApproachChild.bThreeText = " ";
        wolfApproachChild.bFourText = " ";
        wolfApproachChild.bFiveText = " ";
        wolfApproachChild.mainImage = Resources.Load<Sprite>(" ");
        wolfApproachChild.childImage = null;
        wolfApproachChild.leaderImage = null;
        wolfApproachChild.shamanImage = null;
        wolfApproachChild.dogImage = null;
        wolfApproachChild.hunterImage = null;
        wolfApproachChild.displayedImage = wolfApproachChild.mainImage;
        wolfApproachChild.bOneLinkedEvent = "Something else";
        wolfApproachChild.bTwoLinkedEvent = "Something else";
        wolfApproachChild.bThreeLinkedEvent = "Something else";
        wolfApproachChild.bFourLinkedEvent = "Something else";
        wolfApproachChild.bFiveLinkedEvent = "Something else";
        allEvents.Add("wolfApproachChild", wolfApproachChild);
        //
        Event wolfApproachShaman = new Event();
        wolfApproachShaman.mainDescription = "The Shaman is more of a cat person, and the wolf knows it. The group runs away. (+wisdom)";
        wolfApproachShaman.bOneText = " ";
        wolfApproachShaman.bTwoText = " ";
        wolfApproachShaman.bThreeText = " ";
        wolfApproachShaman.bFourText = " ";
        wolfApproachShaman.bFiveText = " ";
        wolfApproachShaman.mainImage = Resources.Load<Sprite>(" ");
        wolfApproachShaman.childImage = null;
        wolfApproachShaman.leaderImage = null;
        wolfApproachShaman.shamanImage = null;
        wolfApproachShaman.dogImage = null;
        wolfApproachShaman.hunterImage = null;
        wolfApproachShaman.displayedImage = wolfApproachShaman.mainImage;
        wolfApproachShaman.bOneLinkedEvent = "Something else";
        wolfApproachShaman.bTwoLinkedEvent = "Something else";
        wolfApproachShaman.bThreeLinkedEvent = "Something else";
        wolfApproachShaman.bFourLinkedEvent = "Something else";
        wolfApproachShaman.bFiveLinkedEvent = "Something else";
        allEvents.Add("wolfApproachShaman", wolfApproachShaman);
        //
        Event wolfFlee = new Event();
        wolfFlee.mainDescription = "-	Not knowing what the Dire wolf is or what bizarre universe it originated from, the group decide to leave it well enough alone. (+wisdom)";
        wolfFlee.bOneText = " ";
        wolfFlee.bTwoText = " ";
        wolfFlee.bThreeText = " ";
        wolfFlee.bFourText = " ";
        wolfFlee.bFiveText = " ";
        wolfFlee.mainImage = Resources.Load<Sprite>(" ");
        wolfFlee.childImage = null;
        wolfFlee.leaderImage = null;
        wolfFlee.shamanImage = null;
        wolfFlee.dogImage = null;
        wolfFlee.hunterImage = null;
        wolfFlee.displayedImage = wolfInit.mainImage;
        wolfFlee.bOneLinkedEvent = "Something else";
        wolfFlee.bTwoLinkedEvent = "Something else";
        wolfFlee.bThreeLinkedEvent = "Something else";
        wolfFlee.bFourLinkedEvent = "Something else";
        wolfFlee.bFiveLinkedEvent = "Something else";
        allEvents.Add("wolfFlee", wolfFlee);
        //
        //
        //
        Event treeInit = new Event();
        treeInit.mainDescription = "Before the group is an enormous tree towering into the sky. Its boughs could conceal many a bountiful reward.";
        treeInit.bOneText = "Have the Leader climb the tree";
        treeInit.bTwoText = "Have the Hunter climb the tree";
        treeInit.bThreeText = "Have the Dog climb the tree";
        treeInit.bFourText = "Have the Child climb the tree";
        treeInit.bFiveText = "Have the Shaman climb the tree";
        treeInit.mainImage = Resources.Load<Sprite>(" ");
        treeInit.childImage = null;
        treeInit.leaderImage = null;
        treeInit.shamanImage = null;
        treeInit.dogImage = null;
        treeInit.hunterImage = null;
        treeInit.displayedImage = treeInit.mainImage;
        treeInit.bOneLinkedEvent = "treeLeader";
        treeInit.bTwoLinkedEvent = "treeHunter";
        treeInit.bThreeLinkedEvent = "treeDog";
        treeInit.bFourLinkedEvent = "treeChild";
        treeInit.bFiveLinkedEvent = "treeShaman";
        allEvents.Add("treeInit", treeInit);
        //
        Event treeLeader = new Event();
        treeLeader.mainDescription = "The Leader is hit with a terrible case of vertigo and refuses to climb the tree.";
        treeLeader.bOneText = " ";
        treeLeader.bTwoText = " ";
        treeLeader.bThreeText = " ";
        treeLeader.bFourText = " ";
        treeLeader.bFiveText = " ";
        treeLeader.mainImage = Resources.Load<Sprite>(" ");
        treeLeader.childImage = null;
        treeLeader.leaderImage = null;
        treeLeader.shamanImage = null;
        treeLeader.dogImage = null;
        treeLeader.hunterImage = null;
        treeLeader.displayedImage = treeLeader.mainImage;
        treeLeader.bOneLinkedEvent = "Something else";
        treeLeader.bTwoLinkedEvent = "Something else";
        treeLeader.bThreeLinkedEvent = "Something else";
        treeLeader.bFourLinkedEvent = "Something else";
        treeLeader.bFiveLinkedEvent = "Something else";
        allEvents.Add("treeLeader", treeLeader);
        //
        Event treeHunter = new Event();
        treeHunter.mainDescription = "The Hunter skilfully scales the tree. Among the branches he finds a plethora of fresh fruit.  (+food + optimism)";
        treeHunter.bOneText = " ";
        treeHunter.bTwoText = " ";
        treeHunter.bThreeText = " ";
        treeHunter.bFourText = " ";
        treeHunter.bFiveText = " ";
        treeHunter.mainImage = Resources.Load<Sprite>(" ");
        treeHunter.childImage = null;
        treeHunter.leaderImage = null;
        treeHunter.shamanImage = null;
        treeHunter.dogImage = null;
        treeHunter.hunterImage = null;
        treeHunter.displayedImage = treeHunter.mainImage;
        treeHunter.bOneLinkedEvent = "Something else";
        treeHunter.bTwoLinkedEvent = "Something else";
        treeHunter.bThreeLinkedEvent = "Something else";
        treeHunter.bFourLinkedEvent = "Something else";
        treeHunter.bFiveLinkedEvent = "Something else";
        allEvents.Add("treeHunter", treeHunter);
        //
        Event treeDog = new Event();
        treeDog.mainDescription = "Dogs can’t climb trees, silly. (+wisdom)";
        treeDog.bOneText = " ";
        treeDog.bTwoText = " ";
        treeDog.bThreeText = " ";
        treeDog.bFourText = " ";
        treeDog.bFiveText = " ";
        treeDog.mainImage = Resources.Load<Sprite>(" ");
        treeDog.childImage = null;
        treeDog.leaderImage = null;
        treeDog.shamanImage = null;
        treeDog.dogImage = null;
        treeDog.hunterImage = null;
        treeDog.displayedImage = treeDog.mainImage;
        treeDog.bOneLinkedEvent = "Something else";
        treeDog.bTwoLinkedEvent = "Something else";
        treeDog.bThreeLinkedEvent = "Something else";
        treeDog.bFourLinkedEvent = "Something else";
        treeDog.bFiveLinkedEvent = "Something else";
        allEvents.Add("treeDog", treeDog);
        //
        Event treeChild = new Event();
        treeChild.mainDescription = "The Child, barely standing three feet off the ground, grabs the nearest branch and pulls it down with all the might his tiny body can muster. But his efforts are not enough, and the branch springs back out of his hands, catapulting and unsuspecting squirrel into the stratosphere. (+optimism)";
        treeChild.bOneText = " ";
        treeChild.bTwoText = " ";
        treeChild.bThreeText = " ";
        treeChild.bFourText = " ";
        treeChild.bFiveText = " ";
        treeChild.mainImage = Resources.Load<Sprite>(" ");
        treeChild.childImage = null;
        treeChild.leaderImage = null;
        treeChild.shamanImage = null;
        treeChild.dogImage = null;
        treeChild.hunterImage = null;
        treeChild.displayedImage = treeChild.mainImage;
        treeChild.bOneLinkedEvent = "Something else";
        treeChild.bTwoLinkedEvent = "Something else";
        treeChild.bThreeLinkedEvent = "Something else";
        treeChild.bFourLinkedEvent = "Something else";
        treeChild.bFiveLinkedEvent = "Something else";
        allEvents.Add("treeChild", treeChild);
        //
        Event treeShaman = new Event();
        treeShaman.mainDescription = "The Shaman composes a beautiful and thoughtful prayer to the tree gods. Unfortunately, there aren’t any tree gods. (+wisdom)";
        treeShaman.bOneText = " ";
        treeShaman.bTwoText = " ";
        treeShaman.bThreeText = " ";
        treeShaman.bFourText = " ";
        treeShaman.bFiveText = " ";
        treeShaman.mainImage = Resources.Load<Sprite>(" ");
        treeShaman.childImage = null;
        treeShaman.leaderImage = null;
        treeShaman.shamanImage = null;
        treeShaman.dogImage = null;
        treeShaman.hunterImage = null;
        treeShaman.displayedImage = treeShaman.mainImage;
        treeShaman.bOneLinkedEvent = "Something else";
        treeShaman.bTwoLinkedEvent = "Something else";
        treeShaman.bThreeLinkedEvent = "Something else";
        treeShaman.bFourLinkedEvent = "Something else";
        treeShaman.bFiveLinkedEvent = "Something else";
        allEvents.Add("treeShaman", treeShaman);
        //
        //
        //
        Event sticksInit = new Event();
        sticksInit.mainDescription = "Look! A pile of sticks!";
        sticksInit.bOneText = "Have the Hunter create something out of sticks";
        sticksInit.bTwoText = "Have the Leader create something out of sticks";
        sticksInit.bThreeText = "Have the Dog create something out of sticks";
        sticksInit.bFourText = "Have the Child create something out of sticks";
        sticksInit.bFiveText = "Have the Shaman create something out of sticks";
        sticksInit.mainImage = Resources.Load<Sprite>(" ");
        sticksInit.childImage = null;
        sticksInit.leaderImage = null;
        sticksInit.shamanImage = null;
        sticksInit.dogImage = null;
        sticksInit.hunterImage = null;
        sticksInit.displayedImage = sticksInit.mainImage;
        sticksInit.bOneLinkedEvent = "sticksHunter";
        sticksInit.bTwoLinkedEvent = "sticksLeader";
        sticksInit.bThreeLinkedEvent = "sticksDog";
        sticksInit.bFourLinkedEvent = "sticksChild";
        sticksInit.bFiveLinkedEvent = "sticksShaman";
        allEvents.Add("sticksInit", sticksInit);
        //
        Event sticksHunter = new Event();
        sticksHunter.mainDescription = "The Hunter builds a 5-storey mansion out of the sticks, complete with a pool and a gym. He leases it to a squirrel for a handful of nuts.(+food + wisdom)";
        sticksHunter.bOneText = " ";
        sticksHunter.bTwoText = " ";
        sticksHunter.bThreeText = " ";
        sticksHunter.bFourText = " ";
        sticksHunter.bFiveText = " ";
        sticksHunter.mainImage = Resources.Load<Sprite>(" ");
        sticksHunter.childImage = null;
        sticksHunter.leaderImage = null;
        sticksHunter.shamanImage = null;
        sticksHunter.dogImage = null;
        sticksHunter.hunterImage = null;
        sticksHunter.displayedImage = sticksHunter.mainImage;
        sticksHunter.bOneLinkedEvent = "Something else";
        sticksHunter.bTwoLinkedEvent = "Something else";
        sticksHunter.bThreeLinkedEvent = "Something else";
        sticksHunter.bFourLinkedEvent = "Something else";
        sticksHunter.bFiveLinkedEvent = "Something else";
        allEvents.Add("sticksHunter", sticksHunter);
        //
        Event sticksLeader = new Event();
        sticksLeader.mainDescription = "The Leader adds one final stick to the pitiful hut he has crafted. It collapses. (+wisdom)";
        sticksLeader.bOneText = " ";
        sticksLeader.bTwoText = " ";
        sticksLeader.bThreeText = " ";
        sticksLeader.bFourText = " ";
        sticksLeader.bFiveText = " ";
        sticksLeader.mainImage = Resources.Load<Sprite>(" ");
        sticksLeader.childImage = null;
        sticksLeader.leaderImage = null;
        sticksLeader.shamanImage = null;
        sticksLeader.dogImage = null;
        sticksLeader.hunterImage = null;
        sticksLeader.displayedImage = sticksLeader.mainImage;
        sticksLeader.bOneLinkedEvent = "Something else";
        sticksLeader.bTwoLinkedEvent = "Something else";
        sticksLeader.bThreeLinkedEvent = "Something else";
        sticksLeader.bFourLinkedEvent = "Something else";
        sticksLeader.bFiveLinkedEvent = "Something else";
        allEvents.Add("sticksLeader", sticksLeader);
        //
        Event sticksDog = new Event();
        sticksDog.mainDescription = "The Dog has a great time playing with the sticks. (+optimism)";
        sticksDog.bOneText = " ";
        sticksDog.bTwoText = " ";
        sticksDog.bThreeText = " ";
        sticksDog.bFourText = " ";
        sticksDog.bFiveText = " ";
        sticksDog.mainImage = Resources.Load<Sprite>(" ");
        sticksDog.childImage = null;
        sticksDog.leaderImage = null;
        sticksDog.shamanImage = null;
        sticksDog.dogImage = null;
        sticksDog.hunterImage = null;
        sticksDog.displayedImage = sticksDog.mainImage;
        sticksDog.bOneLinkedEvent = "Something else";
        sticksDog.bTwoLinkedEvent = "Something else";
        sticksDog.bThreeLinkedEvent = "Something else";
        sticksDog.bFourLinkedEvent = "Something else";
        sticksDog.bFiveLinkedEvent = "Something else";
        allEvents.Add("sticksDog", sticksDog);
        //
        Event sticksChild = new Event();
        sticksChild.mainDescription = "The Child crafts a wooden pickaxe from the sticks and begins mining for diamonds. (+wisdom)";
        sticksChild.bOneText = " ";
        sticksChild.bTwoText = " ";
        sticksChild.bThreeText = " ";
        sticksChild.bFourText = " ";
        sticksChild.bFiveText = " ";
        sticksChild.mainImage = Resources.Load<Sprite>(" ");
        sticksChild.childImage = null;
        sticksChild.leaderImage = null;
        sticksChild.shamanImage = null;
        sticksChild.dogImage = null;
        sticksChild.hunterImage = null;
        sticksChild.displayedImage = sticksChild.mainImage;
        sticksChild.bOneLinkedEvent = "Something else";
        sticksChild.bTwoLinkedEvent = "Something else";
        sticksChild.bThreeLinkedEvent = "Something else";
        sticksChild.bFourLinkedEvent = "Something else";
        sticksChild.bFiveLinkedEvent = "Something else";
        allEvents.Add("sticksChild", sticksChild);
        //
        Event sticksShaman = new Event();
        sticksShaman.mainDescription = "The Shaman makes a series of creepy voodoo people. She swears she isn’t a witch.";
        sticksShaman.bOneText = " ";
        sticksShaman.bTwoText = " ";
        sticksShaman.bThreeText = " ";
        sticksShaman.bFourText = " ";
        sticksShaman.bFiveText = " ";
        sticksShaman.mainImage = Resources.Load<Sprite>(" ");
        sticksShaman.childImage = null;
        sticksShaman.leaderImage = null;
        sticksShaman.shamanImage = null;
        sticksShaman.dogImage = null;
        sticksShaman.hunterImage = null;
        sticksShaman.displayedImage = sticksShaman.mainImage;
        sticksShaman.bOneLinkedEvent = "Something else";
        sticksShaman.bTwoLinkedEvent = "Something else";
        sticksShaman.bThreeLinkedEvent = "Something else";
        sticksShaman.bFourLinkedEvent = "Something else";
        sticksShaman.bFiveLinkedEvent = "Something else";
        allEvents.Add("sticksShaman", sticksShaman);
    }


    void Update () 
	{
		
	}
}
